version: 1
labels:
  - label: "github"
    files:
      - ".github/.*"
  - label: "infrastructure"
    files:
      - "infrastructure/.*"
  - label: "api"
      files:
        - "api/.*"
  - label: "python"
      files:
        - "*/.*/python"