# The cloudbuild.yaml file purpose is to build and push the dockerized version of django webapp.
# TODO: Dockerize djnago webapp.

steps:
  # Use docker build step to build image.
  # It will uses the Dockerfile defined at the root path: `front`
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}", "."]

  # Push the previous built docker image to google container registry(gcr).
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

# Use substitutions https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
substitutions:
  _SERVICE_NAME: "postgres"
