# Generated by Django 4.0.5 on 2022-06-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_framework_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
